name: bilibili-video-provider


on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 0/2 * * *'

jobs:
  bilibili-video-job:

    runs-on: ubuntu-latest

    steps:

    # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # NodeJS 环境
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: '14.x'
        registry-url: https://registry.npmjs.org
        scope: '@octocat'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: npm install

    - name: Run
      env:
        BASE_URL: ${{secrets.BASE_URL}}
        HEADER_TOKEN: ${{secrets.HEADER_TOKEN}}
      run: node bilibili.js
